import Image from "next/image";
import { sanitizeHtml, type BlockSettings } from "@/lib/cms/blocks/schema";
import type { PublicStoryBlock } from "@/lib/cms/public-stories";
const cls=(s:BlockSettings&Record<string,unknown>)=>["story-block",`story-block--${s.width||"content"}`,`story-block--${s.alignment||"left"}`,`story-block--${s.spacing||"normal"}`,`story-block--theme-${s.theme||"default"}`].join(" ");
export function HeadingBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;const Tag=(`h${[2,3,4].includes(d.level)?d.level:2}`) as keyof React.JSX.IntrinsicElements;return <div className={cls(block.settings)}><Tag>{d.text}</Tag></div>}
export function RichTextBlock({block}:{block:PublicStoryBlock}){return <div className={cls(block.settings)}><div className="story-rich-text" dangerouslySetInnerHTML={{__html:sanitizeHtml(String((block.data as any).html||""))}} /></div>}
function figure(d:any,s:any,className=""){return <figure className={`story-figure ${className}`}><div className={`story-image story-image--${s.imageRatio||"natural"}`}><Image src={d.url} alt={d.alt||""} fill sizes={s.width==="full"?"100vw":"(min-width: 1200px) 1080px, 92vw"} style={{objectFit:s.imageFit==="contain"?"contain":"cover",objectPosition:`${(d.focalX??.5)*100}% ${(d.focalY??.5)*100}%`}} /></div>{d.caption&&<figcaption>{d.caption}</figcaption>}</figure>}
export function ImageBlock({block}:{block:PublicStoryBlock}){return <div className={cls(block.settings)}>{figure(block.data,block.settings)}</div>}
export function ImageTextSplitBlock({block}:{block:PublicStoryBlock}){const d=block.data as any,s=block.settings as any;return <section className={`${cls(s)} story-split story-split--${d.mediaPosition||s.mediaPosition||"left"} story-split--${s.splitRatio||"50-50"} story-split--${s.mobileOrder||"media-first"}`}><div>{figure(d,s)}</div><div className="story-split-copy">{d.eyebrow&&<p className="eyebrow">{d.eyebrow}</p>}{d.heading&&<h2>{d.heading}</h2>}<div className="story-rich-text" dangerouslySetInnerHTML={{__html:sanitizeHtml(String(d.text||""))}} />{d.cta?.href&&<a className="button button--primary" href={d.cta.href}>{d.cta.label}</a>}</div></section>}
export function GalleryBlock({block}:{block:PublicStoryBlock}){const d=block.data as any,s=block.settings as any;return <div className={cls(s)}><div className={`story-gallery story-gallery--${s.galleryLayout||"grid"}`}>{(d.items||[]).map((item:any,i:number)=><div key={i}>{figure(item,{...s,imageRatio:s.imageRatio||"landscape"})}</div>)}</div></div>}
export function QuoteBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <div className={cls(block.settings)}><figure className="story-quote"><blockquote>{d.quote}</blockquote>{(d.author||d.role||d.source)&&<figcaption>{d.author}{d.role&&<span> · {d.role}</span>}{d.source&&<cite> — {d.source}</cite>}</figcaption>}</figure></div>}
export function YoutubeBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <div className={cls(block.settings)}><figure><div className="story-video"><iframe src={`https://www.youtube-nocookie.com/embed/${d.videoId}?rel=0&start=${d.startTime||0}`} title={d.title||"Dove video"} loading="lazy" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div>{d.caption&&<figcaption>{d.caption}</figcaption>}</figure></div>}
export function CalloutBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <aside className={`${cls(block.settings)} story-callout story-callout--${d.tone||"info"}`}>{d.title&&<h2>{d.title}</h2>}<div dangerouslySetInnerHTML={{__html:sanitizeHtml(String(d.text||""))}} /></aside>}
export function ButtonGroupBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <div className={`${cls(block.settings)} story-buttons`}>{(d.buttons||[]).map((b:any,i:number)=><a className={`button ${b.variant==="secondary"?"button--secondary":"button--primary"}`} href={b.href} rel={/^https?:/.test(b.href)?"noopener noreferrer":undefined} key={i}>{b.label}</a>)}</div>}
export function SectionIntroBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <header className={`${cls(block.settings)} story-section-intro`}>{d.eyebrow&&<p className="eyebrow">{d.eyebrow}</p>}<h2>{d.title}</h2>{d.leadText&&<p className="lede">{d.leadText}</p>}</header>}
export function DividerBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <div className={cls(block.settings)}><hr className={`story-divider story-divider--${d.style||"line"}`} /></div>}
export function SpacerBlock({block}:{block:PublicStoryBlock}){const d=block.data as any;return <div aria-hidden="true" className={`story-spacer story-spacer--${d.height||"medium"}`} />}
export const blockRenderers={heading:HeadingBlock,rich_text:RichTextBlock,image:ImageBlock,image_text_split:ImageTextSplitBlock,gallery:GalleryBlock,quote:QuoteBlock,youtube:YoutubeBlock,callout:CalloutBlock,button_group:ButtonGroupBlock,section_intro:SectionIntroBlock,divider:DividerBlock,spacer:SpacerBlock} as const;
