import Image from "next/image";
import type { Locale } from "@/i18n/config";
import { links } from "@/content/links";
import { doveMedia } from "@/content/dove-media";
import { contactEn } from "@/i18n/messages/contact-copy";
import { contactEs } from "@/i18n/messages/contact-es-copy";

export function ContactPage({ locale }: { locale: Locale }) {
  const copy = locale === "es" ? contactEs : contactEn;
  const email = links.email.executiveDirector.replace("mailto:", "");
  const routes = [
    [copy.routing.general, email, copy.routing.email, "#contact-form"],
    [copy.routing.volunteer, links.email.volunteer.replace("mailto:", ""), copy.routing.volunteerCta, links.volunteer.page(locale)],
    [copy.routing.sponsorship, links.email.childSponsorship.replace("mailto:", ""), copy.routing.sponsorCta, links.childSponsorship(locale)],
    [copy.routing.travel, email, copy.routing.travelCta, links.travel.page(locale)],
  ];
  const socials = [["Instagram", links.social.instagram, copy.social.instagram], ["Twitter", links.social.twitter, copy.social.twitter], ["Facebook", links.social.facebook, copy.social.facebook], ["LinkedIn", links.social.linkedin, copy.social.linkedin], ["Tripadvisor", links.social.tripadvisor, copy.social.tripadvisor], ["TikTok", links.social.tiktok, copy.social.tiktok]];
  return <main className="contact-page">
    <section className="contact-hero page-shell"><div><p className="eyebrow">{copy.hero.eyebrow}</p><h1>{copy.hero.heading}</h1><p className="lede">{copy.hero.description}</p><div className="hero-actions"><a className="button button--primary" href="#contact-options">{copy.hero.primary}</a><a className="text-link" href="#find-us">{copy.hero.secondary} <span aria-hidden>â†—</span></a></div></div><div className="contact-hero-media"><Image src={doveMedia.contact.hero.src} alt={doveMedia.contact.hero.alt} width={1200} height={900} priority /></div></section>
    <section id="contact-options" className="section section--paper"><div className="page-shell"><p className="eyebrow">{copy.routing.eyebrow}</p><h2>{copy.routing.heading}</h2><p className="section-intro">{copy.routing.description}</p><div className="contact-ledger">{routes.map(([title,address,cta,href],i)=><article className="contact-ledger-row" key={title}><span className="ledger-index">0{i+1}</span><div><h3>{title}</h3><a className="contact-route-email" href={`mailto:${address}`}>{address}</a></div><a className="text-link" href={href}>{cta} <span aria-hidden>â†—</span></a></article>)}</div><div className="contact-phone-band"><strong>{copy.routing.phone}</strong><a href={links.phone.dominicanRepublic}>{copy.routing.dominican}: +1 809 676 4071</a><a href={links.phone.unitedStates}>{copy.routing.unitedStates}: +1 612 442 5974</a></div></div></section>
    <section id="find-us" className="section contact-map"><div className="page-shell"><p className="eyebrow">{copy.map.eyebrow}</p><h2>{copy.map.heading}</h2><p className="section-intro">{copy.map.description}</p><div className="map-layout"><iframe title={copy.map.title} src={links.location.embed} loading="lazy" allowFullScreen referrerPolicy="no-referrer-when-downgrade" /><aside><p className="map-location">{copy.map.location}</p><p>{copy.map.note}</p><a className="button button--primary" href={links.location.directions} target="_blank" rel="noopener noreferrer">{copy.map.directions} â†—</a><a className="text-link" href={links.travel.page(locale)}>{copy.map.visit} <span aria-hidden>â†’</span></a></aside></div></div></section>
    <section id="contact-form" className="section section--paper contact-form-section"><div className="page-shell"><div><p className="eyebrow">{copy.form.eyebrow}</p><h2>{copy.form.heading}</h2><p className="section-intro">{copy.form.description}</p></div><form className="contact-form" action={`mailto:${email}`} method="post" encType="text/plain"><div className="form-grid"><label>{copy.form.firstName}<input name="firstName" required autoComplete="given-name" /></label><label>{copy.form.lastName}<input name="lastName" required autoComplete="family-name" /></label></div><label>{copy.form.email}<input name="email" type="email" required autoComplete="email" /></label><label>{copy.form.phone}<input name="phone" type="tel" autoComplete="tel" /></label><label>{copy.form.reason}<select name="reason" defaultValue="general"><option value="general">{copy.form.general}</option><option value="programs">{copy.form.programs}</option><option value="volunteer">{copy.form.volunteer}</option><option value="travel">{copy.form.travel}</option><option value="sponsorship">{copy.form.sponsorship}</option><option value="partnership">{copy.form.partnership}</option><option value="donation">{copy.form.donation}</option><option value="other">{copy.form.other}</option></select></label><label>{copy.form.message}<textarea name="message" rows={6} required /></label><button className="button button--primary" type="submit">{copy.form.submit}</button><p className="form-fallback">{copy.form.fallback} <a href={`mailto:${email}`}>{email}</a></p></form></div></section>
    <section className="section contact-social"><div className="page-shell"><p className="eyebrow">{copy.social.eyebrow}</p><h2>{copy.social.heading}</h2><p className="section-intro">{copy.social.description}</p><div className="social-grid">{socials.map(([name,href,cta])=><a key={name} href={href} target="_blank" rel="noopener noreferrer"><span>{name}</span><small>{cta} â†—</small></a>)}</div></div></section>
    <section className="section contact-bridge"><div className="page-shell"><p className="eyebrow">{copy.bridge.eyebrow}</p><h2>{copy.bridge.heading}</h2><nav className="bridge-links" aria-label={copy.bridge.heading}><a href={links.travel.page(locale)}>{copy.bridge.travel} â†—</a><a href={links.volunteer.page(locale)}>{copy.bridge.volunteer} â†—</a><a href={links.childSponsorship(locale)}>{copy.bridge.sponsor} â†—</a><a href={links.donate(locale)}>{copy.bridge.donate} â†—</a></nav></div></section>
  </main>;
}
