// @ts-nocheck
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse } from "dotenv";
import { Client } from "pg";

const env = parse(readFileSync(resolve(process.cwd(), ".env.local")));
if (!env.POSTGRES_URL_NON_POOLING) throw new Error("Missing POSTGRES_URL_NON_POOLING");
const connectionString = env.POSTGRES_URL_NON_POOLING.replace(/([?&])sslmode=[^&]+&?/, (_match, lead) => lead === "?" ? "?" : "").replace(/\?$/, "");
const client = new Client({ connectionString, ssl: { rejectUnauthorized: false } });

type LocaleCopy = { title: string; slug: string; eyebrow: string; headline: string; excerpt: string; body: string };
type Candidate = {
  key: string; startDate: string | null; endDate: string | null; location: string | null; goal: number | null; raised: number | null;
  progressSource: "none" | "external" | "manual"; provider: "network_for_good" | null; externalId: string | null; donationUrl: string | null;
  en: LocaleCopy; es: LocaleCopy; sources: Array<{ type: "wix_page" | "network_for_good"; url: string; title: string; metadata?: Record<string, unknown> }>;
  storyLinks: Array<{ title: string; relationship: "announcement" | "update" | "result" | "related" }>;
};

const candidates: Candidate[] = [
  { key: "climb-with-purpose-2026", startDate: null, endDate: null, location: "Pico Duarte, Dominican Republic", goal: 30000, raised: 13641, progressSource: "external", provider: "network_for_good", externalId: "260914", donationUrl: "https://dovemissions.networkforgood.com/projects/260914-summit-for-their-future-climb-with-purpose-2026",
    en: { title: "Climb With Purpose 2026", slug: "climb-with-purpose-2026", eyebrow: "2026 campaign", headline: "To the summit for their future.", excerpt: "A community climb connected supporters with a $30,000 goal to sponsor 50 children for one year of support at Dove.", body: "<p>Climb With Purpose brought supporters, staff, and friends together around Pico Duarte and the everyday perseverance of Dove’s young people. Supporters could participate in person, take part virtually, sponsor a climber, or give directly.</p><p>The campaign source confirms a $30,000 goal and uses $600 as the reference for one year of support for one child. The exact climb dates remain under client review because Dove’s legacy page and the giving provider published different dates.</p>" },
    es: { title: "Climb With Purpose 2026", slug: "climb-with-purpose-2026", eyebrow: "Campaña de 2026", headline: "Hacia la cima por su futuro.", excerpt: "Una caminata comunitaria reunió a colaboradores en torno a una meta de US$30,000 para apoyar a 50 niños durante un año en Dove.", body: "<p>Climb With Purpose reunió a colaboradores, personal y amistades de Dove alrededor del Pico Duarte y de la perseverancia que los jóvenes demuestran cada día. Era posible participar de forma presencial o virtual, apoyar a un caminante o donar directamente.</p><p>La fuente de la campaña confirma una meta de US$30,000 y utiliza US$600 como referencia para un año de apoyo a un niño. Las fechas exactas siguen pendientes de confirmación porque la página histórica de Dove y el proveedor de donaciones publicaron fechas distintas.</p>" },
    sources: [{ type: "wix_page", url: "https://www.doveyouthdevelopment.org/climb-with-purpose", title: "Climb With Purpose 2026", metadata: { reported_dates: "May 28-30, 2026", date_discrepancy: true, source_language: "en" } }, { type: "network_for_good", url: "https://dovemissions.networkforgood.com/projects/260914-summit-for-their-future-climb-with-purpose-2026", title: "To the Summit for Their Future: Climb with Purpose 2026", metadata: { reported_dates: "March 23-25, 2026", goal: 30000, reported_raised_snapshot: 13641, raised_is_final: false, children_goal: 50, annual_support_reference: 600, date_discrepancy: true, source_language: "en" } }], storyLinks: [] },
  { key: "weekend-with-the-pros-2025", startDate: "2025-05-01", endDate: "2025-05-04", location: "Puerto Plata, Dominican Republic", goal: null, raised: null, progressSource: "none", provider: null, externalId: null, donationUrl: null,
    en: { title: "Weekend With The Pros 2025", slug: "weekend-with-the-pros-2025", eyebrow: "May 1–4, 2025", headline: "Sports, community, and a weekend in support of Dove.", excerpt: "A four-day charitable event in Puerto Plata combined golf, youth sports clinics, community connection, and support for Dove Youth Development.", body: "<p>Weekend With The Pros brought sports enthusiasts and professionals together in Puerto Plata for golf, youth clinics, community activities, and support for Dove. This historical page preserves the event’s purpose without retaining expired booking offers.</p>" },
    es: { title: "Weekend With The Pros 2025", slug: "weekend-with-the-pros-2025", eyebrow: "1–4 de mayo de 2025", headline: "Deporte, comunidad y un fin de semana en apoyo a Dove.", excerpt: "Un evento benéfico de cuatro días en Puerto Plata combinó golf, clínicas deportivas juveniles, comunidad y apoyo a Dove Youth Development.", body: "<p>Weekend With The Pros reunió en Puerto Plata a amantes y profesionales del deporte para compartir golf, clínicas juveniles, actividades comunitarias y apoyo a Dove. Esta página histórica conserva el propósito del evento sin mantener ofertas de reserva vencidas.</p>" },
    sources: [{ type: "wix_page", url: "https://www.doveyouthdevelopment.org/wwtp", title: "Weekend With The Pros", metadata: { source_language: "en", obsolete_booking_cta_removed: true } }], storyLinks: [] },
  { key: "2023-school-uniform-drive", startDate: null, endDate: null, location: "Puerto Plata, Dominican Republic", goal: null, raised: null, progressSource: "none", provider: null, externalId: null, donationUrl: null,
    en: { title: "2023 School Uniform Drive", slug: "2023-school-uniform-drive", eyebrow: "2023 campaign", headline: "Helping students return to school prepared.", excerpt: "Dove’s 2023 school uniform initiative brought the community together around a clear back-to-school need.", body: "<p>This campaign archive connects the original drive and its later countdown update without duplicating the full Story content. The related Stories preserve the deeper narrative and source context.</p>" },
    es: { title: "Campaña de uniformes escolares 2023", slug: "campana-uniformes-escolares-2023", eyebrow: "Campaña de 2023", headline: "Ayudando a los estudiantes a regresar preparados a clases.", excerpt: "La iniciativa de uniformes escolares de Dove en 2023 reunió a la comunidad alrededor de una necesidad concreta para el regreso a clases.", body: "<p>Este archivo conecta la campaña original y su actualización de cuenta regresiva sin duplicar el contenido completo de las Historias. Las Historias relacionadas conservan la narración y el contexto de la fuente.</p>" },
    sources: [{ type: "wix_page", url: "https://www.doveyouthdevelopment.org/post/2023-school-uniform-drive", title: "2023 School Uniform Drive", metadata: { source_language: "en", dates_unverified: true } }], storyLinks: [{ title: "2023 School Uniform Drive", relationship: "announcement" }, { title: "Back To School Uniform Countdown", relationship: "update" }] },
  { key: "2022-school-uniform-campaign", startDate: null, endDate: null, location: "Puerto Plata, Dominican Republic", goal: 8500, raised: 2515, progressSource: "manual", provider: null, externalId: null, donationUrl: null,
    en: { title: "2022 School Uniform Campaign", slug: "2022-school-uniform-campaign", eyebrow: "2022 campaign", headline: "One school-year need, told across three updates.", excerpt: "Dove’s 2022 uniform fundraiser moved from announcement to progress update to a reported result supporting 130 children returning to school.", body: "<p>The July update reported $2,515 raised toward an $8,500 goal. That figure is preserved as a point-in-time update, not a final total. A later Story reported that 130 children received support returning to school.</p>" },
    es: { title: "Campaña de uniformes escolares 2022", slug: "campana-uniformes-escolares-2022", eyebrow: "Campaña de 2022", headline: "Una necesidad escolar contada a través de tres actualizaciones.", excerpt: "La campaña de uniformes de Dove pasó del anuncio a una actualización de progreso y luego a un resultado informado: 130 niños apoyados en su regreso a clases.", body: "<p>La actualización de julio informó US$2,515 recaudados de una meta de US$8,500. La cifra se conserva como una actualización de ese momento, no como un total final. Una Historia posterior informó que 130 niños recibieron apoyo para regresar a clases.</p>" },
    sources: [{ type: "wix_page", url: "https://www.doveyouthdevelopment.org/post/june-2022-annual-school-uniform-fundraiser", title: "June 2022 - Annual School Uniform Fundraiser", metadata: { source_language: "en", reported_raised_snapshot: 2515, raised_is_final: false, goal: 8500, reported_children_supported: 130, dates_unverified: true } }], storyLinks: [{ title: "June 2022 - Annual School Uniform Fundraiser", relationship: "announcement" }, { title: "July 2022 - Back to School Help Needed", relationship: "update" }, { title: "Back to School Backpacks", relationship: "result" }] },
];

async function run() {
  await client.connect(); await client.query("BEGIN");
  const run = await client.query("INSERT INTO dove.migration_runs(source,status,stats) VALUES ('dove_historical_campaigns','running','{}') RETURNING id"); const runId = run.rows[0].id;
  const stats = { campaigns_discovered: candidates.length, campaigns_imported: 0, campaigns_skipped: 0, stories_linked: 0, sources_recorded: 0, media_reused: 0, warnings: [] as string[], ambiguous_candidates: ["Giving Tuesday 2022", "Christmas giving initiatives", "Weekend With The Pros 2024", "Vocational fundraising pushes", "Sponsor recruitment drives"] };
  try {
    for (const item of candidates) {
      const existing = await client.query("SELECT campaign_id FROM dove.campaign_sources WHERE source_type=$1 AND source_url=$2 LIMIT 1", [item.sources[0].type, item.sources[0].url]);
      if (existing.rowCount) { stats.campaigns_skipped++; continue; }
      let heroMediaId: string | null = null;
      for (const link of item.storyLinks) { const match = await client.query("SELECT s.cover_media_id FROM dove.stories s JOIN dove.story_translations st ON st.story_id=s.id WHERE lower(st.title)=lower($1) LIMIT 1", [link.title]); if (match.rows[0]?.cover_media_id) { heroMediaId = match.rows[0].cover_media_id; stats.media_reused++; break; } }
      const campaign = await client.query(`INSERT INTO dove.campaigns(status,hero_media_id,start_date,end_date,lifecycle_override,location,goal_amount,currency,raised_amount,raised_amount_is_final,progress_source,progress_updated_at,external_provider,external_campaign_id,donation_url,published_at) VALUES ('published',$1,$2,$3,'ended',$4,$5,'USD',$6,false,$7,CASE WHEN $6::numeric IS NULL THEN NULL ELSE now() END,$8,$9,$10,now()) RETURNING id`, [heroMediaId, item.startDate, item.endDate, item.location, item.goal, item.raised, item.progressSource, item.provider, item.externalId, item.donationUrl]);
      const campaignId = campaign.rows[0].id; stats.campaigns_imported++;
      for (const locale of ["en", "es"] as const) { const copy = item[locale]; const translation = await client.query("INSERT INTO dove.campaign_translations(campaign_id,locale,slug,title,eyebrow,headline,excerpt,seo_title,seo_description,publication_status) VALUES ($1,$2,$3,$4,$5,$6,$7,$4,$7,'published') RETURNING id", [campaignId, locale, copy.slug, copy.title, copy.eyebrow, copy.headline, copy.excerpt]); await client.query("INSERT INTO dove.campaign_blocks(campaign_translation_id,block_type,sort_order,data,settings,visible) VALUES ($1,'rich_text',0,$2,$3,true)", [translation.rows[0].id, JSON.stringify({ html: copy.body }), JSON.stringify({ width: "narrow", spacing: "generous", alignment: "left", theme: "default" })]); }
      for (const [index, source] of item.sources.entries()) { const checksum = createHash("sha256").update(JSON.stringify(source)).digest("hex"); await client.query("INSERT INTO dove.campaign_sources(campaign_id,source_type,source_url,source_title,source_checksum,metadata,last_verified_at) VALUES ($1,$2,$3,$4,$5,$6,now())", [campaignId, source.type, source.url, source.title, checksum, JSON.stringify(source.metadata ?? {})]); stats.sources_recorded++; }
      for (const [index, link] of item.storyLinks.entries()) { const story = await client.query("SELECT s.id,st.slug,s.legacy_wix_url,s.legacy_wix_id,st.title FROM dove.stories s JOIN dove.story_translations st ON st.story_id=s.id WHERE lower(st.title)=lower($1) AND st.locale='en' LIMIT 1", [link.title]); if (!story.rowCount) { stats.warnings.push(`Story not found: ${link.title}`); continue; } const row = story.rows[0]; await client.query("INSERT INTO dove.campaign_story_links(campaign_id,story_id,relationship_type,sort_order) VALUES ($1,$2,$3,$4) ON CONFLICT DO NOTHING", [campaignId, row.id, link.relationship, index]); stats.stories_linked++; if (row.legacy_wix_url) { await client.query("INSERT INTO dove.campaign_sources(campaign_id,source_type,source_id,source_url,source_title,source_checksum,metadata,last_verified_at) VALUES ($1,'wix_post',$2,$3,$4,$5,$6,now()) ON CONFLICT DO NOTHING", [campaignId, row.legacy_wix_id ?? row.id, row.legacy_wix_url, row.title, createHash("sha256").update(row.legacy_wix_url).digest("hex"), JSON.stringify({ relationship_type: link.relationship, source_language: "en" })]); stats.sources_recorded++; } }
      if (item.key === "climb-with-purpose-2026") await client.query("INSERT INTO dove.redirects(source_path,destination_path,status_code,active) VALUES ('/climb-with-purpose','/en/campaigns/climb-with-purpose-2026',301,true) ON CONFLICT (source_path) DO NOTHING");
      if (item.key === "weekend-with-the-pros-2025") await client.query("INSERT INTO dove.redirects(source_path,destination_path,status_code,active) VALUES ('/wwtp','/en/campaigns/weekend-with-the-pros-2025',301,true) ON CONFLICT (source_path) DO NOTHING");
    }
    await client.query("UPDATE dove.migration_runs SET status='completed',completed_at=now(),stats=$2 WHERE id=$1", [runId, JSON.stringify(stats)]); await client.query("COMMIT");
    console.log(JSON.stringify({ runId, ...stats, expectedSecondRunNew: 0 }, null, 2));
  } catch (error) { await client.query("ROLLBACK"); throw error; } finally { await client.end(); }
}
run().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
